export interface IService {
    ser_id: number
    ser_key: any
    parent_id: number
    banner_show: any
    show_type: any
    category_type: string
    category_section: string
    design_type: string
    video_type: string
    service_cat_id: any
    service_type: any
    service_name: string
    name_desc: any
    description2: any
    service_image: string
    service_banner_image: string
    home_banner_image: any
    video_link: any
    alt_tag?: string
    description?: string
    homedescription: any
    short_desc?: string
    section: any
    title_tag: any
    keyword_tag: any
    description_tag: any
    canonical_tag: any
    url: string
    status: string
    ser_status: string
    ser_attr: any
    created_by: number
    updated_by: any
    deleted_by: any
    order_by: any
    created_at: string
    updated_at: string
    deleted_at: any
  }
  