export interface IBlog {
  blg_id: number
  blog_key: any
  blog_show_type: string
  blog_type: string
  name: string
  dr_description: string
  blog_name: string
  short_desc: string
  blog_description?: string
  blog_image: string
  alt_image_name: any
  blog_image_inner: string
  tags: any
  title_tag: any
  keyword_tag: any
  description_tag: any
  canonical: any
  url: string
  status: string
  blog_status: string
  blog_attr: any
  date: string
  created_by: number
  updated_by: number
  deleted_by: any
  created_at: string
  updated_at: string
  deleted_at: any
}
