export interface IDoctor{
  doc_id: number
  doctor_key: any
  show_type: string
  name: string
  short_degree: string
  sort_desc: any
  description: any
  home_image: string
  home_desc: string
  image: any
  image2: any
  banner_image: string
  alt_tag: any
  education_desc: any
  education_detail: any
  experience_desc: any
  experience_detail: any
  section: string
  title_tag: any
  keyword_tag: any
  description_tag: any
  canonical_tag: any
  url: string
  order_by: any
  status: string
  doctor_status: string
  doctor_attr: any
  created_by: number
  updated_by?: number
  deleted_by: any
  created_at: string
  updated_at: string
  deleted_at: any
}